### ISSUE TITLE
redis消息队列存在严重bug

### ISSUE THREAD

**Issue by youminxue** [yuchanns/gobyexample#1]
消费过程中，其他协程把消费中的消息移动到消息队列中，这样会导致消息一直删除不掉

**Comment by youminxue** [comment]
ack环节会把其他协程刚刚消费的数据再次加入队列这有就会出现问题

**Comment by yuchanns** [comment]
感谢反馈，元旦的时候我修复一下

**Comment by yuchanns** [comment]
> ack环节会把其他协程刚刚消费的数据再次加入队列这有就会出现问题

https://github.com/yuchanns/gobyexample/blob/ef98f7f5f0f986fcdefe260bcd5b6f7ae2e0dc0e/queue/queue.go#L94-L125

你好，可能是我注释不够充分的缘故，也许导致你没有正确理解。在此说明一下。`doingQueue`是根据`number`做了命名区分的，目的就是为了防止ack产生多goroutine竞争。
```go
doingQueue := fmt.Sprintf("%s.doing%d", msg.GetChannel(), number)
```
需要注意的是这里的number是`go func(ctx context, number int){...}`中的number，也就是外部for循环的`i`，这个值需要被传入这个goroutine，而不是通过直接引用的方式，否则会发生i大概率都是同一个值的情况。

而在这些措施下，每个goroutine的doingQueue都是独立的不会有交叉，并且正常情况下在每个独立的goroutine的循环中doingQueue一次只会有一个数据，反言之，如果存在多个对象，说明是因为进程崩溃或其他异常退出导致没有消费掉，所以被ack函数取回预备队列，此时可被其他goroutine正常消费。

直接运行这里的源代码应该不存在消费竞争的bug。

你看看是不是这里产生了误解导致了bug的“发生”？

另外这是个比较简陋的原型，如果有功能缺乏，请多见谅。经过多次迭代后，现在生产上已经采用了消息总线+webhook的机制，方便管理和控制大数量消费者的场景。

期待你的反馈。
